env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
rules:
  semi: 
    - 2
    - always
  indent:
    - error
    - 2
    - SwitchCase: 1
